### ISSUE TITLE
Not working in Anki ⁨23.12.1

### ISSUE THREAD

**Issue by oatmilklatte** [gregorias/anki-image-scaler#18]
Hello, thank you for creating this add on! My issue is that the add on will resize in the editor window but it does not resize the actual card after closing the editor window.

**Comment by gregorias** [comment]
Could you provide screenshots of what you see, so that I better understand the difference between what you see and what you expect?

**Comment by oatmilklatte** [comment]
[image: image.png]

[image: image.png]
it also makes me confirm the max height multiple times/forces 150 as max
height

[image: image.png]

[image: image.png]

**Comment by gregorias** [comment]
![grafik](https://github.com/gregorias/anki-image-scaler/assets/722385/cf0c2b42-130f-455a-bd51-c81ea7306048)

I don’t see anything.

**Comment by gregorias** [comment]
Closing as abandoned. Feel free to reopen.
