### ISSUE TITLE
New update causes ModuleNotFoundError

### ISSUE THREAD

**Issue by cps9716** [gregorias/anki-image-scaler#4]
I've just updated the Scale Image addon, and received this notification upon opening Anki after installation:

" An add-on you installed failed to load. If problems persist, please go to the Tools>Add-ons menu, and disable or delete the add-on.
When loading '⁨Scale Images⁩':
⁨Traceback (most recent call last):
  File "aqt/addons.py", line 230, in loadAddons
  File "/Users/******/Library/Application Support/Anki2/addons21/1312865748/__init__.py", line 3, in <module>
    from . import main
  File "/Users/******/Library/Application Support/Anki2/addons21/1312865748/main.py", line 13, in <module>
    from PyQt6.QtWidgets import QInputDialog, QWidget
ModuleNotFoundError: No module named 'PyQt6' "

I just wanted to bring this to your attention. Please let me know if there is anything I need to do to resolve this. Thank you very much.

**Comment by Mark99193** [comment]
I got the same issue!
Very frustrating because I love this add-on!

**Comment by gregorias** [comment]
Thanks for reporting. I'll revert and add regression tests.
